Doc fix and one more gitignore
rcsb/py-rcsbsearchapi pull request #35
Opened 2024-02-09 19:47 UTC by josemduarte

The script didn't work directly because python didn't like a positional parameter after a non-positional parameter

2024-02-09 19:59 UTC, piehld requested changes
Thanks @josemduarte! Can you just bump the minor version too, in both these files:

- https://github.com/rcsb/py-rcsbsearchapi/blob/master/rcsbsearchapi/__init__.py
- https://github.com/rcsb/py-rcsbsearchapi/blob/master/CHANGELOG.md

Also, for future reference, we typically like to follow the PR process below:

```
dev-branch -> staging -> master
dev-branch2 --^
```
That way, we can bundle changes into a single PR. But since this is just a minor patch, OK to go directly to master.

2024-02-09 20:05 UTC, piehld commented
@josemduarte Sorry, I mean bump the patch, not the minor version.

2024-02-09 22:41 UTC, josemduarte commented
Happy to bump the version, but my changes are not touching the code at all (just docs and ancillary stuff). Would you bump the version in that case too?

2024-02-12 15:12 UTC, piehld approved these changes

2024-02-12 15:13 UTC, piehld commented
Good point, in that case we can just merge. I updated a couple other places where this example shows up too.

2024-02-12 15:13 UTC, merged